# Generated by Django 5.1.3 on 2024-12-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id_order', models.IntegerField(primary_key=True, serialize=False)),
                ('id_cart', models.IntegerField()),
                ('id_address', models.IntegerField()),
                ('id_cupon', models.IntegerField()),
                ('id_employee', models.IntegerField()),
                ('id_status', models.IntegerField()),
                ('order_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Order_status',
            fields=[
                ('id_status', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.TextField()),
            ],
        ),
    ]
