# Generated by Django 5.1.3 on 2024-12-06 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pedidos', '0001_initial'),
        ('moduloDespacho', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id_cart',
            field=models.ForeignKey(db_column='id_cart', on_delete=django.db.models.deletion.CASCADE, to='gestion_pedidos.shoppingcart'),
        ),
    ]
