# Generated by Django 5.1.3 on 2024-12-06 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pedidos', '0001_initial'),
        ('moduloDespacho', '0002_alter_order_id_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id_address',
            field=models.ForeignKey(db_column='id_address', on_delete=django.db.models.deletion.CASCADE, to='gestion_pedidos.customeraddress'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id_cupon',
            field=models.ForeignKey(db_column='id_cupon', on_delete=django.db.models.deletion.CASCADE, to='gestion_pedidos.coupon'),
        ),
    ]
