# Generated by Django 5.1.3 on 2024-12-06 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pedidos', '0001_initial'),
        ('moduloDespacho', '0003_alter_order_id_address_alter_order_id_cupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id_cupon',
            field=models.ForeignKey(blank=True, db_column='id_cupon', null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_pedidos.coupon'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id_employee',
            field=models.ForeignKey(db_column='id_employee', on_delete=django.db.models.deletion.CASCADE, to='gestion_pedidos.employee'),
        ),
    ]
