# Generated by Django 5.1.3 on 2024-12-04 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id_configuration', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('slogan', models.CharField(max_length=256)),
                ('color_pallete', models.CharField(max_length=256)),
                ('address', models.TextField()),
                ('isPointsActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id_cupon', models.AutoField(primary_key=True, serialize=False)),
                ('cupon_code', models.CharField(max_length=256)),
                ('cupon_disount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('exp_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=256, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('firstname', models.CharField(max_length=256)),
                ('lastName', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id_municipio', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id_status', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='RewardPoints',
            fields=[
                ('id_points', models.AutoField(primary_key=True, serialize=False)),
                ('exp_date', models.DateTimeField()),
                ('points_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAddresses',
            fields=[
                ('id_address', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='gestion_pedidos.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id_distrito', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('id_municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distritos', to='gestion_pedidos.municipio')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('count', models.IntegerField()),
                ('dailyMenuDate', models.DateField(blank=True, null=True)),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='gestion_pedidos.category')),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id_detail', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='gestion_pedidos.product')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='id_points',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_pedidos.rewardpoints'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id_employee', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=256)),
                ('lastName', models.CharField(max_length=256)),
                ('username', models.CharField(max_length=256, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('isActive', models.BooleanField(default=True)),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='gestion_pedidos.rol')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id_cart', models.AutoField(primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_carts', to='gestion_pedidos.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id_order', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField()),
                ('id_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='gestion_pedidos.customeraddresses')),
                ('id_cupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_pedidos.cupon')),
                ('id_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='gestion_pedidos.employee')),
                ('id_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='gestion_pedidos.orderstatus')),
                ('id_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='gestion_pedidos.shoppingcart')),
            ],
        ),
    ]
