# Generated by Django 5.1.3 on 2024-12-03 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('path_logo', models.CharField(max_length=100)),
                ('path_slogan', models.CharField(max_length=100)),
                ('color_pallette', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('isPointActive', models.BooleanField(default=False)),
            ],
        ),
    ]
