# Generated by Django 5.1.3 on 2024-12-08 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_administracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='color_pallette_bg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
