# Generated by Django 5.1.3 on 2024-12-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
