# Generated by Django 5.1.3 on 2024-12-07 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'managed': False},
        ),
    ]
