# Generated by Django 5.1.3 on 2024-12-04 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_administracion', '0004_alter_configuration_id_alter_customer_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='idconfigurationPast',
            new_name='configurationPast',
        ),
    ]
