# Generated by Django 4.2.16 on 2024-12-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_administracion', '0005_rename_idconfigurationpast_configuration_configurationpast'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_descuento', models.CharField(choices=[('PORCENTAJE', 'Descuento Porcentual'), ('MONTO_FIJO', 'Descuento Monto Fijo')], max_length=20)),
                ('valor_descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_vencimiento', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
                ('uso_maximo', models.IntegerField(default=1)),
            ],
        ),
    ]
