# Generated by Django 4.2.16 on 2024-12-06 23:40

from django.db import migrations

def create_roles(apps, schema_editor):
    # Create roles
    Role = apps.get_model('modulo_administracion', 'Role')
    roles = [
        "Administrador",
        "Encargado de menú",
        "Encargado de registro de pedidos",
        "Encargado de despacho de pedido",
        "Repartidor",
    ]
    for role_name in roles:
        Role.objects.get_or_create(name=role_name)

class Migration(migrations.Migration):

    dependencies = [
        ('modulo_administracion', '0006_cupon'),
    ]

    operations = [
        migrations.RunPython(create_roles),
    ]
