# Generated by Django 4.2.16 on 2024-12-07 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_administracion', '0006_cupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='configurationPast',
        ),
    ]
