# Generated by Django 5.1.3 on 2024-12-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id_points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
